version: '3'

services:
  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot" ]
      timeout: 10s
      retries: 10
      start_period: 10s

  backend:
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      API_PORT: 3001
      MYSQL_URI: "mysql://root:root@mysql:3306/todos"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:3001/health" ]
      timeout: 10s
      retries: 10
    command: bash -c "npm run db && npm start"

  frontend:
    build: ./frontend
    depends_on:
      backend:
        condition: service_healthy
    environment:
      API_URI: "http://localhost:3001"
    ports:
      - 3000:80
